; PlatformIO Project Configuration File

[platformio]
src_dir     = src
default_envs = megaatmega2560

; -- Arduino Mega 2560 (FreeRTOS, preemptive) -------------------------
[env:megaatmega2560]
platform  = atmelavr
board     = megaatmega2560
framework = arduino
lib_deps  =
    feilipu/FreeRTOS@^11.1.0-3
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    Keypad
    paulstoffregen/OneWire
    milesburton/DallasTemperature@^4.0.6
build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -lm
monitor_speed = 9600
monitor_echo  = yes
monitor_eol   = LF
